### ISSUE TITLE
Hold shift while drawing to draw straight lines

### ISSUE THREAD

**Issue by captainbrosset** [juliandescottes/piskel#146]
I use this a lot in photoshop and find it very useful when working at the pixel level.
This should work with pen, vertical mirror pen and eraser. Holding the shift key while drawing should only allow drawing in straight lines (perhaps in 45deg diagonals too).

**Comment by juliandescottes** [comment]
Bumping this,  will implement an alt mode on the stroke tool.
When holding SHIFT, the line will be limited to X/Y axes or 45deg diagonals.
