### ISSUE TITLE
Enhancement : Option to switch to repeated preview 

### ISSUE THREAD

**Issue by juliandescottes** [juliandescottes/piskel#190]
From http://www.reddit.com/r/gamedev/comments/28uxd9/piskel_new_online_pixel_art_app_for_creating/

When drawing tiles, it's useful to see the sprite repeated in the preview. 

There is already a hidden setting that enables that (`javascript:pskl.UserSettings.set(pskl.UserSettings.TILED_PREVIEW,!pskl.UserSettings.get(pskl.UserSettings.TILED_PREVIEW))`) need to add a UI to control this setting now.

**Comment by juliandescottes** [comment]
Fix will be released on v0.5.0

**Comment by andycorm** [comment]
Does this feature have a control on the GUI within production yet? I love this feature, but I can't always remember the javascript console command of the top of my head :p

(Also, as a random side note THANK YOU FOR MAKING PISKEL!! Using Photoshop was such a pain in the tail for working on pixel art, and it's wonderful having such a great free tool that's accessible anywhere.)

**Comment by juliandescottes** [comment]
In the application settings panel, there is now a "repeated preview" checkbox : 

![image](https://cloud.githubusercontent.com/assets/1141550/11962144/de4688f8-a8dd-11e5-9e5e-e89107f5b3b2.png)

Not the best UI ever, but better than having to run JS manually :)

And thanks for the nice words !
