### ISSUE TITLE
Import/export animation json data

### ISSUE THREAD

**Issue by devnewton** [juliandescottes/piskel#191]
It would  be nice to get json animation data with the zipped png images.

I use the following format for my own [animation software](http://devnewton.bci.im/en/softwares/nanim) and games:

https://github.com/devnewton/newton_adventure/blob/master/game/data/default_level_data/hero.json

**Comment by hassanshaikley** [comment]
Bumping this : )

I am trying to use piskel with pixi js and JSON would be so great! : )

**Comment by juliandescottes** [comment]
Just merged #581 ! Thanks.
