### ISSUE TITLE
Enhancement: Multi-png animation support

### ISSUE THREAD

**Issue by hcatlin** [juliandescottes/piskel#192]
When using Apple's SpriteKit to develop games, they always want animations and sequences done like this:

name_000.png
name_000@2.png
name_001.png
name_001@2.png
name_002.png
name_002@2.png
name_003.png
name_003@2.png

I know it's kind of a simple / dumb feature to add, but being able to get these out would be FREAKING AMAZING to the pipeline of someone building OS X / iPhone games.

**Comment by juliandescottes** [comment]
This was fixed by #214 AFAICT. Feel free to reopen if needed!
