### ISSUE TITLE
Enhancement  :  Alpha

### ISSUE THREAD

**Issue by je2mz** [juliandescottes/piskel#210]
I know that retro-styled games typically doesn't have alpha within the animations, however I think it would be a great addition to add in an alpha percentage for the current color. We could get some sweet looking effects in a game that can look semi-modern but retro at the same time! ie. hyper light drifter/super time force.

**Comment by juliandescottes** [comment]
Duplicate of #434

**Comment by N0BEH** [comment]
Can we imagine a static image mode one day, rather than a systematic gif mode? Would managing the alpha channel of an image color on export be just as complex? How many of us export only a png rather than a gif?
