### ISSUE TITLE
Feature: Trim drawing area

### ISSUE THREAD

**Issue by zdeveloperlane** [juliandescottes/piskel#224]
I uploaded a new feature that does:  ( https://github.com/zdeveloperlane/piskel )

Expand:
Computes the used area of all layers and frames; and will add extra border pixels to left, right, top, bottom AND shift the data to maintain current animation (like adding padding). This is very useful for creating animations as nobody really knows their canvas size when starting, and we all hate to lose alignment when resizing things. IT made sense to be in the resize menu since it's expensive

Trim:
Computes the used area of all layers and frames; Shifts all data to fit in this box, and resizes to fit the minimum area used. This is useful before exporting, as you can then Expand to make your gif fit whatever you like

What do you think? Is it okay to add a new issue for each thing I add in or? Are there comment standards I should use? Are you having a good day? I hope so! XD

**Comment by juliandescottes** [comment]
Renaming the issue to focus on Trim feature. The resize improvement will be delivered with v0.5.0.

Only thing remaining is to be able to trim.
