### ISSUE TITLE
Request for instructions to integrate Piskel into other apps

### ISSUE THREAD

**Issue by Actimator** [juliandescottes/piskel#232]
Piskel is a great tool for game development environments like Actimator. Would you consider providing instructions on how to integrate Piskel into other applications?

**Comment by juliandescottes** [comment]
I'm not planning to work on embedding.

Here's an example of what is possible right now : https://github.com/juliandescottes/piskel-embed
Have a look there, see what's missing for you.

If you have specific changes/APIs you would like to see integrated in piskel to ease embedding, open specific issues.

Thanks !
