### ISSUE TITLE
Export spritesheets with sizes that constrain to powers of 2

### ISSUE THREAD

**Issue by LuckySvenn** [juliandescottes/piskel#247]
Hey, I really like your application!

But it would be really nice to maybe have a checkmark box that could change the width and height sizes of the spritesheet to only powers of 2.

So, let's say I've got a spritesheet that's about to be exported that is currently 160x32. It'd be nice to check a checkmark box that does something like changes 160 to 256.

I work with engines that require textures that constrain to the power of 2 for rendering quality, and this would be really useful for me!

Thanks!

**Comment by juliandescottes** [comment]
Let's say we have 4 frames @ 40x32 => spritesheet of 160x32.
  - should it be resized (scaled up) to 256*51 ? 
  - should it be 256*32, with something to fill the empty space ?

(What is the name of the engine you are using ?)

**Comment by LuckySvenn** [comment]
The latter implementation.

I'm using libGDX, and in their [wiki](https://github.com/libgdx/libgdx/wiki/Spritebatch%2C-Textureregions%2C-and-Sprites) under the 'Texture' header, it suggest using textures with dimensions that are powers of 2.

**Comment by juliandescottes** [comment]
Will be fixed with #473, closing as duplicate.
