### ISSUE TITLE
Feature : detached popup preview

### ISSUE THREAD

**Issue by juliandescottes** [juliandescottes/piskel#250]
When animating big sprites, the existing animated preview is too small to preview correctly your work.
Allow to display the animated preview in a separate popup.

**Comment by juliandescottes** [comment]
Something like this :)
![image](https://cloud.githubusercontent.com/assets/1141550/6474176/f14c00ca-c1fe-11e4-97df-837cb6c62659.png)

**Comment by Dullgarian** [comment]
Thanks Julian! Can't wait to use this feature!

**Comment by juliandescottes** [comment]
Fixed, will be released in v0.5.0
