### ISSUE TITLE
internal server error whenever i try to login

### ISSUE THREAD

**Issue by TVB3000** [juliandescottes/piskel#254]
picture of issue: http://gyazo.com/a253518d9bcf0f3b5ba7d519d1a03cdd

whenever i go onto the homepage and click login it presents me with this message even though it was working fine yesterday. not sure if it's a problem on my end either :/

**Comment by juliandescottes** [comment]
I have no idea what's happening, I can't login as well ...
Will try to investigate today but I will be at work for most of the day :(

**Comment by juliandescottes** [comment]
Looks like it was a technical issue with the hosting service I use.
I restarted one of the servers and I can now login.

Sorry about that.

**Comment by juliandescottes** [comment]
Problem is resolved. Closing the issue.

**Comment by TVB3000** [comment]
thanks :D
