### ISSUE TITLE
Feature: Thickness of Line

### ISSUE THREAD

**Issue by TotallyNotSatan** [juliandescottes/piskel#258]
I think a feature to increase the thickness of the line you draw(say, from one to ten) would be cool. I'm currently making an animation(as in, a 550px by 400px one) on Piskel, and I've found it hard to make detailed animations with a one-pixel-thickness line.

Thanks,

Satan

**Comment by juliandescottes** [comment]
I agree that's a great feature when working on big animations. 

Technically it shouldn't be hard to implement. Not sure how to fit it in the current UI though.

Most editors have a toolbar dedicated to the selected tool, where you can modify options for the tool (such as thickness). I wouldn't like such a UI to be always visible, so I need to figure out how to make this work :)

On the other hand, a global 'thickness' setting could be easier to integrate. It would impact : 
- pens (basic pen, mirror pen, lighten)
- line
- circle
- rectangle

And I guess it could fit between the tools and the color picker.
Maybe a good compromise for the beginning ?

**Comment by neight-bit** [comment]
How about context / panel menus for each tool by double-clicking the tool?

**Comment by juliandescottes** [comment]
Will be implemented with a global control on top or bottom of the tools list. 

![image](https://cloud.githubusercontent.com/assets/1141550/11178884/03ba3daa-8c50-11e5-92bb-aab967593391.png)

**Comment by TotallyNotSatan** [comment]
WOO HOO!

On Mon, Nov 16, 2015 at 1:51 AM, Julian Descottes <notifications@github.com>
wrote:

> Will be implemented with a global control on top or bottom of the tools
> list.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1141550/11178884/03ba3daa-8c50-11e5-92bb-aab967593391.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliandescottes/piskel/issues/258#issuecomment-156973923>
> .
>



-- 
Drew Weisserman
Class of 2019
