### ISSUE TITLE
ctrl-c with no selection - Bad state for CUT callback in SelectionManager

### ISSUE THREAD

**Issue by leegrey** [juliandescottes/piskel#261]
Here's a little bug I encountered early on.

To reproduce, just open the desktop build, and hit ctrl-c without doing anything else. You will go straight to the node-webkit crash screen, with the message, "Uncaught node.js Error. Bad state for CUT callback in SelectionManager". If you draw on the canvas and then hit ctrl-c without a selection, you get the "Your piskel seems to have unsaved changes..." message. If you select ok, it will crash in the same way. 

Ctrl-c works fine if you have a selection, but crashes without one. Maybe just don't throw an error in SelectionManager?

By the way, I noticed that the node-webkit version defined in package.json is v~0.10.1, which is a bit behind. It might be safe enough to say "latest"?

**Comment by juliandescottes** [comment]
Thanks for the report !

Looks like every uncaught exception leads to this in node-webkit. I will review the rest of the project and will swap exceptions for error logs.

**Comment by leegrey** [comment]
I'm not completely sure about this, but can you use `process.on('uncaughtException')` to create a generic exception handler? Then you could just log it from there.

https://nodejs.org/api/process.html

**Comment by juliandescottes** [comment]
Moved all non critical errors to console.error for now. Should reduce the amount of crashes for desktop

WIll be released for v0.5.0
