### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Calinou** [juliandescottes/piskel#268]
Would you add a license, please? See <http://choosealicense.com/> for more information.

**Comment by juliandescottes** [comment]
Thanks for the reminder, I'm reviewing the options at the moment !

**Comment by juliandescottes** [comment]
Now licensed under GPLv2, closing the issue

**Comment by Calinou** [comment]
GPLv3 is probably a better choice.

**Comment by juliandescottes** [comment]
AGPLv3 seems more relaxed, which I prefer. So I switched to it, thanks for the suggestion.

@Calinou : any reason you particularly care about this ? Do you need to reuse the code/program somewhere ?

**Comment by Calinou** [comment]
> @Calinou : any reason you particularly care about this ? Do you need to reuse the code/program somewhere ?

Not particularly – but GPLv3 and AGPLv3 work better to defend user freedom than GPLv2 does.

**Comment by juliandescottes** [comment]
Ok, thanks for the advice !

I've never carefully thought about licensing, so I'm still a bit lost. But AGPLv3 should be OK.
