### ISSUE TITLE
Gallery page looks zoomed in

### ISSUE THREAD

**Issue by captainbrosset** [juliandescottes/piskel#274]
The gallery page seems zoomed in somehow. I have tested this on Chrome and Firefox, and the layout is all messed up.

The logout link wraps on the second line, and the create button is misaligned. Also, the fonts are all very big. And the category links are above the screenshots, not in the left-hand sidebar.

I've verified that my browser wasn't zoomed in (cmd+0).

It may be due to the retina display.

**Comment by captainbrosset** [comment]
On the home page, the font looks ok:
![screenshot 2015-04-28 15 37 28](https://cloud.githubusercontent.com/assets/1152698/7370731/86b3fed6-edbc-11e4-90bd-3072519d886a.png)

Whenever I reach my gallery page:
![screenshot 2015-04-28 15 37 36](https://cloud.githubusercontent.com/assets/1152698/7370734/87f2abf8-edbc-11e4-88b3-8f258adf3e53.png)

**Comment by captainbrosset** [comment]
The font-size difference seems to come from this media query:

```
@media screen and (min-resolution: 1.5dppx) {
  body {
    font-size : 2em;
  }
```

**Comment by juliandescottes** [comment]
This issue was moved to juliandescottes/piskel-website#3
