### ISSUE TITLE
Suggestion: Batch actions on gallery

### ISSUE THREAD

**Issue by guilnunes** [juliandescottes/piskel#279]
I think it might be useful to have:
On the gallery screen, add a checkbox on the image thumbnails, so you can use actions on multiple images, like:

-delete many images
-make public/private
-export as (png,gif,etc)

Or if possible in the future:
-move to a folder
-make the folder private/public

**Comment by juliandescottes** [comment]
True ! Thanks.

**Comment by juliandescottes** [comment]
This issue was moved to juliandescottes/piskel-website#4
