### ISSUE TITLE
Suggestion: Embedding Into Other Web Apps

### ISSUE THREAD

**Issue by ericrosas** [juliandescottes/piskel#280]
Any thoughts on supporting the embedding of Piskel into other web apps? I'm contributing towards an HTML5 game engine that can build retro 3D games and it would be killer to embed Piskel for texture editing and sprite creation.

**Comment by juliandescottes** [comment]
I'm not planning to work on embedding.

Here's an example of what is possible right now : https://github.com/juliandescottes/piskel-embed
Have a look there, see what's missing for you.

If you have specific changes/APIs you would like to see integrated in piskel to ease embedding, open specific issues.

Thanks !
