### ISSUE TITLE
Export GIF looses transparent pixel

### ISSUE THREAD

**Issue by GuerkanDemirci** [juliandescottes/piskel#282]
1.) Load GIF
2.) Make some pixels transparent
3.) Export GIF

Failure: Exported GIF has no transparent pixels

**Comment by juliandescottes** [comment]
Looks like there are still bugs with the transparent GIF export. Doesn't happen with every sprite though.

Can you share a sprite where you have the issue ? Ideally a .piskel file, or a link to a saved sprite ?

Thanks.

**Comment by GuerkanDemirci** [comment]
it works with other exported gifs.

but doesn't work with this one in my public gallery: http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgICQptiKCQw/view

Filling the gray background with transparent color and then exporting it as GIF will result in non transparent yellow background.

**Comment by juliandescottes** [comment]
Ok after some testing it looks like it happens when the image contains more than 256 colors. Your imported GIF here has more than a thousand colors. 

Depending on the number of colours I rely on different algorithm to encode to GIF. If < 256, I preserve all colors and everything's fine. If > 256 I need to simplify the color index. Looks like it doesn't work well with the 'transparency setting'.

Will have a look, thanks for the info !

**Comment by GuerkanDemirci** [comment]
thank you for the information
(I even didn't know that GIFs are allowed to have more then 256 colors)

**Comment by juliandescottes** [comment]
If you are interested : they can have up to 256 colors per frame. 1

And you can also abuse this a bit : see https://webmasters.stackexchange.com/questions/304/can-i-have-an-animated-gif-with-more-than-256-colours-per-frame

![lots of colors !](http://i.stack.imgur.com/GjMPe.gif)

**Comment by GuerkanDemirci** [comment]
interesting.

The original gif has a global color table. The first image descriptor has no local color table, hence is using the global color table. The second image descriptor has a local color table. etc.

The exported gif has a similar structure. But the "transparency flag" is set in the "graphics control extension block". That is correct.

I don't know how the transparency color index is applied when there is a local color table defined.

But somehow the transparency is incorrect when there is a local color table defined as in this image.

**Comment by juliandescottes** [comment]
I modified the minified code of the gif library I use, and probably screw something up. I backported my change properly on my fork, built it again. And now it works.

Will need

**Comment by juliandescottes** [comment]
![](http://piskel-imgstore-b.appspot.com/img/0f28fad7-f951-11e4-8e12-39996fd08e19.gif)

Here's a preview of your GIF - with transparency :)

**Comment by GuerkanDemirci** [comment]
quick and immediate fix.  perfect. thank you julian. keep up the good work

**Comment by juliandescottes** [comment]
Just updated piskelapp.com with the fix. 
You should be able to export GIFs with more than 256 colors & transparency.

**Comment by GuerkanDemirci** [comment]
confirming. it's working. thank you very much

**Comment by Tru14** [comment]
This issue is currently happening with me. 

I build a sprite with a transparent background but when I export it as a GIF I lose the transparency.

**Comment by Ahryess** [comment]
> This issue is currently happening with me.
> 
> I build a sprite with a transparent background but when I export it as a GIF I lose the transparency.

same here :(

**Comment by castilloglenn** [comment]
![NFT - Ship](https://user-images.githubusercontent.com/55197203/155880568-28b573a6-2a68-440f-bab7-0ac01189250e.gif)

My boosters seems to have a white background though. How to fix this?

**Comment by derwin12** [comment]
Try with firefox.

**Comment by castilloglenn** [comment]
Thanks, I reconfigured the output parameters and it worked.
