### ISSUE TITLE
404 error on recreation

### ISSUE THREAD

**Issue by ChrisKlinglerOhsome** [juliandescottes/piskel#283]
I'm sure this is simply a beginner error, but I tried to recreate your project from zip and get a 404 error with the source saying that it can't GET piskel-packaged-min.js or piskel-style-packaged.css with piskel-boot.js. From the following lines:

var script;
    if (window.location.href.indexOf('pack') != -1) {
      script = 'js/piskel-packaged' + version + '.js';
    } else {
      script = 'js/piskel-packaged-min' + version + '.js';
    }
    loadStyle('css/piskel-style-packaged' + version + '.css');

Anyone know what I am missing?

**Comment by juliandescottes** [comment]
Hi !

By default, piskel tries to load minified versions of the statics. You can
append ?debug to the URL you target to use the exploded source files.

Have a look at
https://github.com/juliandescottes/piskel/wiki/Development-Environment for
more info :)
Le 17 mai 2015 06:39, "ChrisKlinglerOhsome" <notifications@github.com> a
écrit :

**Comment by ChrisKlinglerOhsome** [comment]
Works perfectly. Thanks Julian
