### ISSUE TITLE
keep all layers in a frame at 100% opacity

### ISSUE THREAD

**Issue by burritojay** [juliandescottes/piskel#286]
It'd be nice to have all layers on a frame be 100% opaque so one can see how the sprite looks, not sure what the idea behind onion skinning them is? Seems like the workflow is: each animation frame can have multiple layers, which is awesome. 

 I've actually hacked this to work using firebug, it's pretty simple. I prefer to use the standalone version though, which I can't hack because I can't wrap my head around the build system. If there is a place to change this behaviour in the pre-built version please let me know.

**Comment by juliandescottes** [comment]
Sorry for the late feedback :(

I think that's a good feature to have. Ideally I'd like to have a way to toggle the preview for each layer.
In the meantime I think the "show layer preview" can have 3 states hidden/full-opacity/low-opacity.

> If there is a place to change this behaviour in the pre-built version please let me know.

I don't think you can hack this on the standalone version :/ 

Did you manage to download and to npm install the project ? (https://github.com/juliandescottes/piskel/wiki/Development-Environment)
After running "grunt desktop" you should have something almost ready to use for OSX & Linux. 
For windows I think I still have to run a small util on top of the artifacts produced by node-webkit, to package the .exe with the icon etc... But it should still be usable as is.

**Comment by juliandescottes** [comment]
Fixed by commit d962217f9048a1cd8f86162fb5973919aa11be70.

**Comment by burritojay** [comment]
Awesome, thanks! :D

**Comment by juliandescottes** [comment]
And just released in v0.5.4 ! Closing the issue.

(new "layer preview opacity" setting in the "general" settings menu)
