### ISSUE TITLE
Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by AlexHolly** [juliandescottes/piskel#287]
Is there any way to set custom shortcuts?
It woul'd be nice to have such a feature.

**Comment by juliandescottes** [comment]
Almost done with the implementation for this feature.

The shortcuts can be modified via the 'cheatsheet' dialog (opened when clicking on the keyboard icon).

I had to take a small shortcut to avoid making this too big. 4 shortcuts cannot be remapped : 
- 1 to 9 for selecting colors
- ctrl + Y for redo
- ? for opening the cheatsheet dialog
- del to clear the current selection

And consequently the keys mapped to those shortcuts cannot be assigned to another shortcut. Other than this, everything is now customisable.

**Comment by juliandescottes** [comment]
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/1141550/10784379/0d085186-7d5e-11e5-8a47-f888aa6fe94a.gif)

**Comment by AlexHolly** [comment]
It's looking good where can I test it?

**Comment by juliandescottes** [comment]
For now it's only in development, so you would need to build the application to test it.

It will be release in v0.6.0 (no release date planned yet :) )

**Comment by juliandescottes** [comment]
Will close after release
