### ISSUE TITLE
Integration Work

### ISSUE THREAD

**Issue by mikeboulet-haw** [juliandescottes/piskel#297]
Hello,

I have a project in progress that would require Piskel to read and write images from an API instead of a local file system. Do you offer integration services?

**Comment by juliandescottes** [comment]
Hi !

No integration services, sorry ! 

I just set up an example of loading the standalone piskel editor in an iframe and loading sprites defined in an external JS file.
Might be helpful for you : https://github.com/juliandescottes/piskel-embed

How did you plan to integrate piskel into your application/environment ?

**Comment by mikeboulet-haw** [comment]
Hi Julian,

I've a developer over at Youth Digital in North Carolina ( youthdigital.com
). We create computer courses for children. Two of our most popular courses
teach children how to mod Minecraft in Java on the client and server
sides.  Our server side course uses a online IDE called Codenvy (
codenvy.com ). We are looking to integrate Piskel into that environment so
that a child can edit Minecraft image assets right out of Codenvy just by
clicking on the image file. Initially we won't be using the animation
features just the pixel editing.

By the way, great job Piskel. We are all really impressed and think it
would be a great experience for children.

Thanks for the example I will take a look at it.

Take care,
Mike

**Comment by juliandescottes** [comment]
Hi Mike !

I don't know how codeenvy works but what you mention seems doable if you're prepared to fork and modify Piskel.

> integrate Piskel into that environment

Would it be the same idea as in my example ? Can you integrate it in an iframe in this editor ? Or were you thinking about something else ?

> edit Minecraft image assets

In my example I use the ".piskel" format to load different sprites. But we could also programmatically call the image importers (they might be mixed with the UI for their controllers for now, but shouldn't be impossible to extract the logic as a service). What is the format of the assets ?

Now you will need to get back the edited image from Piskel. For this you need to override the current save features of Piskel to have something that will send the resulting PNG to your code.

> Initially we won't be using the animation features just the pixel editing

I don't plan to make Piskel configurable enough to hide & prevent the animation part, so this will have to be tuned in your fork. Not difficult to do I think, just a pain to maintain several possible configurations.

**Comment by juliandescottes** [comment]
I'm not planning to work on embedding.

Here's an example of what is possible right now : https://github.com/juliandescottes/piskel-embed
Have a look there, see what's missing for you.

If you have specific changes/APIs you would like to see integrated in piskel to ease embedding, open specific issues.

Thanks !
