### ISSUE TITLE
Saving does not work on desktop

### ISSUE THREAD

**Issue by civilframe** [juliandescottes/piskel#322]
When I go to save a file, it says 
![screen shot 2015-10-24 at 12 53 45 pm](https://cloud.githubusercontent.com/assets/2343514/10712380/45ef98e6-7a4e-11e5-8339-13a755dbad8b.png)

Here's a GIF:
![save does not work](https://cloud.githubusercontent.com/assets/2343514/10712381/4966be6e-7a4e-11e5-87a9-2f0ee998b6ea.gif)

I tried this on Mac OSX Yosemite 10.10.5 and Windows 8.

**Comment by civilframe** [comment]
@juliandescottes If there's any chance you could fix this before November 7th, you would be my hero! I would like to use this tool for a game development workshop for a group of high school girls. It would be ideal to use the desktop version in case we have internet trouble, etc.

**Comment by juliandescottes** [comment]
Thanks for the report ! 

Looks like the button is broken :/ CMD + SHIFT + S works, though should be easy to fix.
I'll have a fix uploaded in one hour max.

**Comment by civilframe** [comment]
Wow! That was fast! Hero :heart:

**Comment by juliandescottes** [comment]
@civilframe no worries :) If you want to give a try to the new versions, they're available at https://github.com/juliandescottes/piskel/wiki/Desktop-applications

Cheers !

**Comment by civilframe** [comment]
Excellent! It works.

![screen shot 2015-10-24 at 3 44 49 pm](https://cloud.githubusercontent.com/assets/2343514/10713134/3d6e7990-7a66-11e5-879b-d992972db680.png)
