### ISSUE TITLE
Offline version fails to start on Ubuntu 15.04 / 15.10, and some other

### ISSUE THREAD

**Issue by cra0zy** [juliandescottes/piskel#323]
First of all the error message is:
```
./piskel: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```
Now I already know what is causing this error. It's the fact that libudev.so.0 has been replaced with libudev.so.1 in newer versions of Ubuntu(and other newer Linux distros). 

I don't know much about javascript apps so can't help here much, but Popcorn Time had the same problem at one stage, so good luck.

In the meantime anyone else getting the same bug can make a symlink:
```
sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
sudo ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
```

**Comment by juliandescottes** [comment]
Thanks for the input ! I admit I didn't test on Linux recently :/

I am using nw.js to package the website as an offline app. Looks like they are aware of the issue and suggest a bunch of workarounds : https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0 

I will pick the most safe/convenient one and use it for the Linux releases.

**Comment by juliandescottes** [comment]
I just uploaded a new version at https://dl.dropboxusercontent.com/u/17803671/piskel/standalone/linux/piskel-0.5.5.2-64bits.zip which should work fine.

The piskel file did not even have the correct permissions ... I fixed this as well.

**Comment by MatiasArriola** [comment]
I've just tried the last link in ubuntu 14.04 64bits and works great :+1:

**Comment by cra0zy** [comment]
I can also confirm that it has fixed the problem.

nice work btw :+1:

**Comment by juliandescottes** [comment]
Thanks for the feedbacl @MatiasArriola & @cra0zy !
