### ISSUE TITLE
Setup Development Environment wiki

### ISSUE THREAD

**Issue by AlexHolly** [juliandescottes/piskel#331]
1.I had to install phantomjs to run "grunt test" it is not listed on the wiki.
I also had to update nodejs after installing it. I suggest to make a setup script to save some time.

I don't know if it contains all what is needed I’ve created it after installing everything manually.

http://pastebin.com/Hqum6HfF

2.I'm also missing API docs to the libs that are used.  I'm new to js and don't know where to look so maybe those two?

https://developer.mozilla.org/en-US/docs/Web/API/
https://nodejs.org/api/

**Comment by juliandescottes** [comment]
These are good points. I don't necessarily want to maintain installation instruction for the different libraries we are using, but we could at least have a link to nodejs, phantomjs, casperjs and explain where each one is required (basically node & grunt are required to build, phantomjs is required to run unit tests, and casperjs required to run the integration tests in headless mode).

Regarding JS and libs, you are right we can point to MDN & Node documentation. We should also have links to the documentation of the libraries we use (jquery, spectrum, tinycolor, jszip). 

And finally, need also to document a bit the current architecture. How to add a new JS, a new CSS, how the Controllers work etc ...

**Comment by juliandescottes** [comment]
Assigning to myself as I am the only one who can edit the wiki ...

**Comment by juliandescottes** [comment]
Phantom js is now installed via npm install. A developer should be able to run npm install and grunt unit-test without any extra step.

**Comment by juliandescottes** [comment]
No extra setup steps required now, closing.
