### ISSUE TITLE
Public URL for PNG?

### ISSUE THREAD

**Issue by johann-gambolputty** [juliandescottes/piskel#341]
Hi,
When I'm rebuilding my game assets I'd like to be able to pull my sprite png files down. I can see there's a gif public url. Is there an equivalent URL based on a sprite ID I can use to get the png?
Many thanks
(p.s. fantastic tool - loving it)

**Comment by juliandescottes** [comment]
Hi !

If your sprite is saved on piskelapp.com, you can use http://www.piskelapp.com/p/{sprite-id}/sprite.
For instance with one of my sprites :  http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgICQ9oSICgw/sprite

It always points to the latest version of your sprite. Is this what you were looking for ? I'm mostly using this for debug purposes so I never thought about highlighting it.

**Comment by johann-gambolputty** [comment]
Perfect! Thank you Julian

**Comment by juliandescottes** [comment]
No change required, closing !
