### ISSUE TITLE
The frame list shouldn't scroll sideways

### ISSUE THREAD

**Issue by captainbrosset** [juliandescottes/piskel#349]
This is a really minor one, but anyway.

Steps:
- create some frames
- start dragging a frame
- move it towards the right

On Firefox at least (haven't tested elsewhere): the frames list scrolls slightly to the left (even though there's no scrollbar). As a result, the left border of the frames isn't visible anymore.

![frames](https://cloud.githubusercontent.com/assets/1152698/11476827/1b572046-9785-11e5-8646-cbaacc1614f0.png)

**Comment by juliandescottes** [comment]
Released in v0.7.0
