### ISSUE TITLE
The bottom overflow image in the frame list is upside down

### ISSUE THREAD

**Issue by captainbrosset** [juliandescottes/piskel#350]
This happens for me on Windows with Firefox 44.

See this image:
![frames](https://cloud.githubusercontent.com/assets/1152698/11476912/88a21fa2-9785-11e5-9063-8b021da7c8ef.png)

As you can see, the bottom of the frame list is supposed to have a nice overflow image that indicates that there are more frames below, but in my case it looks like it's upside down.

**Comment by captainbrosset** [comment]
Also (and this could be related to Windows), the overflow image overlaps with the scrollbar.

**Comment by juliandescottes** [comment]
For your first comment, I would just add this is Firefox only.

The other issue is ... "non-Chrome" specific. Chrome being the only browser where we can easily customize the scrollbars, some absolute positioning & sizes are relying on the scrollbar width which is actually browser specific => let's move this to another issue.
