### ISSUE TITLE
"selected color" marker is not visible if the color is yellow

### ISSUE THREAD

**Issue by captainbrosset** [juliandescottes/piskel#352]
Yes, I know, very nitpicking, but it occurred to me that if your palette has yellow in it, it will be very hard to see the "selected color" marker on it (the yellow triangle that appears in the lower left corner when you click on a color in the palette section).

Maybe some box-shadow could help? Maybe instead of a triangle over the color, a different border color around the color placeholder?

![palette-png](https://cloud.githubusercontent.com/assets/1152698/11477547/cae1130c-9788-11e5-959f-a476481cfa85.PNG)

**Comment by juliandescottes** [comment]
Will be release in v0.8.0

**Comment by juliandescottes** [comment]
![image](https://cloud.githubusercontent.com/assets/1141550/14726011/94eb1db2-081f-11e6-8e17-36efd68571c3.png)
