### ISSUE TITLE
Add 2x, 3x, 4x preview sizes in the Animated Preview

### ISSUE THREAD

**Issue by juliandescottes** [juliandescottes/piskel#362]
In the top right animated-preview, the user can force the preview to be at 1x scale : 
![image](https://cloud.githubusercontent.com/assets/1141550/11668361/0fa45fde-9df7-11e5-89e1-6ee2e7f342ba.png)

But the preview is 200x200 and if the user is doing a 32x32 sprite, the actual preview will be really small.
![image](https://cloud.githubusercontent.com/assets/1141550/11668429/747d4768-9df7-11e5-95fc-ab2240a4bc00.png)

It would be nice to have access to bigger pixel perfect zooms (until it doesn't fit in the 200x200 preview anymore).

An easy first implementation could be to have a single "toggle" button, but with additional states.
By default it would be on the "auto" scale setting, clicking once would move it to 1x, clicking again to 2x etc ... The current scale should be clearly displayed in the UI.

**Comment by GMartigny** [comment]
What size really matter ? x2, x3, x4 ... ?

What could be a good solution of display ?

- A "looping" toggle button, going [inactive => x1 => x2 => x4] and loop
- 3 separate buttons side by side

![fourbuttons](https://cloud.githubusercontent.com/assets/2543511/14738826/12206fa8-0884-11e6-93f6-acb583bd65b1.png)
- Some kind of dropdown on mouse hover

![dropdown](https://cloud.githubusercontent.com/assets/2543511/14739041/768b55d8-0885-11e6-807b-d76fe32ba31e.png)

**Comment by juliandescottes** [comment]
> What size really matter ? x2, x3, x4 ... ?

In theory all scaling factors that still fit in the 200x200 preview for the current animation. But that's a very good question, maybe from a user perspective, only 1x, best(\*) and full(\*\*) matter.

_Inventing definitions on the fly:
(\*) best: the maximum integer scaling factor that fits in 200x200 (ie 6x for a 32x32 picture)
(\*\*) full: the current preview filling 200x200 no matter what_

> A "looping" toggle button, going [inactive => x1 => x2 => x4] and loop

That's what I had in mind as a first step, seems easier to implement. With a shift+click to reverse the loop order maybe?

> 3 separate buttons side by side

Takes too much space IMO. 

> Some kind of dropdown on mouse hover

Why not! How would this UI work if another option than 1x is selected though? I think we have to display the full list of options as well as the selected one.

**Comment by GMartigny** [comment]
> maybe from a user perspective, 1x, best(*) and full(**)

That should do.

> Takes too much space IMO

I agree with that.

> How would this UI work

I had that in mind http://jsbin.com/viqihirufu/ (lousy implementation)
Turn out nice, I guess

**Comment by juliandescottes** [comment]
> I had that in mind http://jsbin.com/viqihirufu/ (lousy implementation)
> Turn out nice, I guess

Really nice!

**Comment by GMartigny** [comment]
Hey, I would like to resurect this issue. Does it still a confirmed feature ?

Final choice go to "x1, best, full" scaling factor with a drop-down ? http://jsbin.com/pejota

**Comment by juliandescottes** [comment]
> Hey, I would like to resurect this issue. Does it still a confirmed feature ?

Welcome back :) And yes, this feature would be welcome!

> Final choice go to "x1, best, full" scaling factor with a drop-down ? 

Let's start with that! Maybe instead of "best" we should just display the scaling factor ?
So for instance for a 32x32 sprite, we would have x1 / x6 / Full.

**Comment by GMartigny** [comment]
How do you see it working with the seamless mode ?
Today, it force preview size to "1x" (without any visual clue). Could become really weird if user can select a preview size.

**Comment by juliandescottes** [comment]
Fixed by @GMartigny

**Comment by hlandau** [comment]
I get 1x, 6x and full zoom sizes, but not 2x. What if I want 2x?

**Comment by GMartigny** [comment]
That's one of the current limitations.
You can only get x1, "best" (biggest round zoom) and "full" (biggest zoom)

IMO, having a slider should be next improvement in this subject.
