### ISSUE TITLE
Zoom where cursor is

### ISSUE THREAD

**Issue by staab** [juliandescottes/piskel#375]
Similar to the PC game Supreme Commander; I'd like to be able to zoom in on the edge of my drawing to do detail work, but zoom focuses on the center, and I can't find a way to pan the view.

**Comment by juliandescottes** [comment]
To move the viewport you can either : 
- drag the white rectangle on the animated preview (top right)
- hold the middle mouse button (or wheel button) and move your cursor

**Comment by staab** [comment]
Ah, that'll do the trick. Thanks.

**Comment by juliandescottes** [comment]
Fixed with #385
