### ISSUE TITLE
Piskel Preview Pane

### ISSUE THREAD

**Issue by supervg123** [juliandescottes/piskel#409]
Well, I did something wrong, and the preview panel for piskel was, well, disoriented. It shows multiple images of my pixel art, and it looked weird. I tried to change the settings, but it's still not fixed.
![screenshot 2016-02-18 at 9 39 36 am](https://cloud.githubusercontent.com/assets/17320414/13152363/9759be38-d623-11e5-9f63-17f2546dfcfb.png)

and the GIF plays like that. Please help.

**Comment by juliandescottes** [comment]
Looks like you activated the repeated preview, it's a check box in the application settings (first menu item on the right)

**Comment by supervg123** [comment]
Looks like I did. Thanks a lot for your help. I really appreciated it. :-)

**Comment by juliandescottes** [comment]
No problem, glad to help!
