### ISSUE TITLE
Layers as an opacity tool?

### ISSUE THREAD

**Issue by Narrowism** [juliandescottes/piskel#414]
So i've been using the layers tool as a way to shade (Did that make any sense?) So basically, I was using the second layer as a way to show light shining off an object, but after I downloaded it, it only showed one layer. I went into the settings and messed around with the opacity tool, but it didn't really help. Is there anyway I can make the second layer show slightly behind the first layer? The preview is different then the actual drawing area, since the preview only shows one layer. Basically, any way I can make the downloaded image look like the second layer is merged with the first?

**Comment by Narrowism** [comment]
can make the downloaded image look like the second layer is merged with the first?

**Comment by Narrowism** [comment]
(attach second comment to 1st comment)

**Comment by fernandodiacenco** [comment]
(I'm not a piskel developer)

Do you mean something like this?

![shade](https://cloud.githubusercontent.com/assets/2643364/13382870/6e556284-de5d-11e5-976d-79b5dd1ec9b8.png)

(The fireball "aura" is on layer 2)

Would that be fixed if the color pallete has support for opacity in colors?

If so I would like the opportunity to suggest adding this possibility on the color palette tool, as it would make easier to add anti-aliasing to sprites made on piskel.

(I apologize if there already is, but I didn’t found it.)

**Comment by Narrowism** [comment]
yes, thats exactly what I mean.

**Comment by juliandescottes** [comment]
Thanks for filing the issue.

Alpha channel/opacity was already discussed a bit. Fully supporting alpha channels in the color palette is way too heavy for the current implementation of Piskel.

Setting an opacity per layer is much more reasonable and could be a nice feature. 

So the goal here would be to : 
- add an opacity/alpha value in the Layer model
- display the layer's alpha value in the layers list
- allow the user to update the alpha [0..1]
- persist the layers alpha settings when saving/loading 
- support the layer alpha when exporting to PNG
- support the layer alpha when exporting to GIF (? this is a bit tricky, we can't have an alpha channel for GIFs so we might need to force a background if any transparent pixel is detected with no background color)
- support the layers alpha in the animated preview
- support the layers alpha in the drawing area (should check what other softwares do here)

Need to check the impact on performance as well : 
- how to fillRect transparent pixels: update the colors vs. set a global opacity?
- try to keep the impact as little as possible for users not using alpha layers
 
I'll take this one.

**Comment by Narrowism** [comment]
Ok... (I am pretty confused right now...) But thanks!

**Comment by juliandescottes** [comment]
@Narrowism sorry if this got confusing. 
Long story short, the feature you are requesting is not imlemented in Piskel at all for the moment. The "layer preview opacity" you can find in the settings only impacts the rendering in the editor. It's a way to tell the program: 
> "when editing a Layer, all the other layers should still be visible but with a reduced opacity so that the current layer always remains visible".

Here what you are asking is to set an opacity per layer and to use this information when exporting to PNG. 

My comment is just the list of items that need to be done when implementing this.
What @fernandodiacenco mentioned (having opacity in colors) would be nice but it is too heavy for Piskel at the moment.

**Comment by Narrowism** [comment]
oh, that ok. maybe you could add that feature  to the offline editor version of Piskel or something. But thanks for responding! :D

**Comment by Narrowism** [comment]
Thanks for working on it so quickly! (I saw what you posted on twitter and thats why i'm back) But thanks!
T

**Comment by juliandescottes** [comment]
Released in v0.7.0

**Comment by Narrowism** [comment]
Hey, been messing around with the feature. Kinda confused on how to use it tho. How do you edit the layer opacity? (Sorry if im annoying you XD)

**Comment by juliandescottes** [comment]
@Narrowism no problem. 

Each layer in the layer list has "1a" by default (alpha = 1). Click on this to edit the value of the layer opacity. This will change the global opacity of this layer. (this is only available on piskelapp.com for now, is this what you are using ?)

In the gif below, I draw a square in one layer, then add a background layer and finally make the layer transparent.

![ezgif-2757754766](https://cloud.githubusercontent.com/assets/1141550/14172286/9a9b77c8-f737-11e5-8f0d-48803021f33a.gif)

**Comment by Narrowism** [comment]
Got it! Thanks for the help :D

**Comment by Narrowism** [comment]
So! Here's a gif of what I know so far.  (I also know that changing the number to something like 0.7 will make it less visible) Anything i'm doing wrong/ don't know about yet?
![piskel](https://cloud.githubusercontent.com/assets/13776966/14173943/4b57febe-f76b-11e5-8d0f-f227eb4370e1.gif)

**Comment by Narrowism** [comment]
Alright, figured everything out. Anything else new that I don't know about :D

**Comment by juliandescottes** [comment]
> I also know that changing the number to something like 0.7 will make it less visible 

The alpha value of a layer can vary between 1 -> fully opaque and 0 -> fully transparent.
I wanted to add a nicer widget to change the opacity, but I ran out of time.

Ideally a range input should popup when clicking on the the alpha value, with some icons to guide the user.

**Comment by Narrowism** [comment]
ok... Thanks! I think you should make the icon to change the transparency bigger, or make it its own tab on the right or something. It would be easier for new people to find it. :D well, thanks for helping me out!

**Comment by fafafrei** [comment]
@juliandescottes Is there an open issue number for the 'nicer widget' to change the opacity?

**Comment by fafafrei** [comment]
@juliandescottes To amend my previous comment: it looks like the popup has changed a bit since the gif above (almost a year ago), but I think an input slider with a little preview of the opacity would be pretty cool.  I just got my Piskel dev environment set up and finally have some free time to help out with this awesome project.  Let me know if this is something you would like me to implement.

**Comment by juliandescottes** [comment]
Great to hear @fafafrei ! I just opened #616 to track this improvement. 
I tried to add as much info as I could, feel free to pick it up!
