### ISSUE TITLE
Allow saving sprites bigger than 1MB

### ISSUE THREAD

**Issue by juliandescottes** [juliandescottes/piskel#437]
AppEngine default object store limits the objects to 1MB.

For now, a psikel is stored as a single object containing a base64 representation of the spritesheet, which can go easily over 1MB when working with a big resolution sprite.
- investigate alternate solutions to store blobs > 1MB
- whatever the new size limit is, display an accurate error message when saving - it would actually be nice to check the size before uploading and to display a warning to the user, even if it's not 100% accurate.

**Comment by mattdinthehouse** [comment]
For client-side or server storage? If it's client-side you could use [localStorage](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage). Wikipedia says it takes at least 5MB.

**Comment by juliandescottes** [comment]
Sorry I should have been more accurate ! This issue is mainly about server side storage, which has a cap of 1MB per object.

For client-side saving we already use localStorage. However the localStorage cap is shared for all objects of a single domain. So if you save a lot of big sprites you will still run into storage issues. And this is problematic since we also use localStorage to manage user preferences. 

Ultimately we should move the client-side save to indexedDB [1].

[1] https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API
