### ISSUE TITLE
Create "Advanced/Custom Export" popup

### ISSUE THREAD

**Issue by juliandescottes** [juliandescottes/piskel#446]
Some export formats can be confusing for beginners and should not be visible in the default export panel. See #440 for example.

As proposed by @clementleger, we could add a button/link in the export panel, that would open a popup containing these advanced export formats. 

The goal of this issue is to
- add the button/link in the export panel
- create the advanced export dialog (with some discussion/agreement about the layout)
- define how new export formats can be added to this popup
- move the C export format to the popup

**Comment by Austech** [comment]
Hey Julian, been messing with this issue. How does this look?

![](http://i.imgur.com/a1MDCxi.png)
![](http://i.imgur.com/XeETxsT.png)

**Comment by Austech** [comment]
Also perhaps we could do something like issue #450 in this advanced panel?

**Comment by juliandescottes** [comment]
Thanks for the suggestion! 
If we use an "advanced/basic options" button, it feels weird to replace the content of the panel. 

But that makes me think we could have tabs actually here. This would allow to really split each export method and also add the much requested option to export a square spritesheet.

![image](https://cloud.githubusercontent.com/assets/1141550/15018962/33524380-121c-11e6-9f7a-87d3064557f2.png)

(ugly mockup)

**Comment by juliandescottes** [comment]
![piskel-export-tabs](https://cloud.githubusercontent.com/assets/1141550/15463616/df8c94cc-20ca-11e6-8d16-325f2c7d8aa7.gif)

Work in progress
