### ISSUE TITLE
Save selected frame

### ISSUE THREAD

**Issue by AlexHolly** [juliandescottes/piskel#450]
Offline Version: piskel-0.6.0-64bits

Is there a way to save the selected frame as .png?

I don't want to save the zip when I just need one of x frames.

**Comment by juliandescottes** [comment]
Sorry, that's not possible. I guess this should be implemented as a frame range (export frames between N and P)
I am not in favor of introducing this in the current UI though. Already too crowded :/

But to be considered if anyone wants to work on an export dialog!

**Comment by AlexHolly** [comment]
Is it possible to add a scrollbar in export so it won't change much on the ui when it's added at the bottom.

**Comment by juliandescottes** [comment]
If anyone wants to pick this up, this feature could easily be added to the "Other" export tab of the export panel now.

![image](https://cloud.githubusercontent.com/assets/1141550/15632341/db8bb538-258e-11e6-94f9-8ff3a5c241be.png)

**Comment by AlexHolly** [comment]
Maybe something like this?
Adding this feature in "misc" will end in a lot duplicate code, this solution contains just a few lines in the PngExporter, html file and PikelRenderer.

![off](https://cloud.githubusercontent.com/assets/4741886/15633262/673debb4-25a8-11e6-99d2-b6aadcbda6ac.png)

![on](https://cloud.githubusercontent.com/assets/4741886/15633238/ee1de0f4-25a7-11e6-8c5b-727bbd627874.png)

**Comment by juliandescottes** [comment]
Sorry, I don't think this should live next to the other options in the "Spritesheet layout" section. 

I would prefer a section in the "others" tab, but a separate section in the PNG tab with a dedicated Download button could work too.

![image](https://cloud.githubusercontent.com/assets/1141550/15633694/466485b8-25b4-11e6-86ca-0c66f7e5ee94.png)


Also I don't think this will lead to duplicated code. Most of the code in the PngExportController is dealing with the layout options which will not be applied when saving a single frame. The PngExportController before today was ~40 lines, and was mostly boilerplate code.

**Comment by juliandescottes** [comment]
Fixed by #550
