### ISSUE TITLE
Rewrite integration tests to use CasperJS >1.1 and PhantomJS >2.0

### ISSUE THREAD

**Issue by islemaster** [juliandescottes/piskel#479]
Right now, the integration tests [have a dependency on CasperJS 1.0.2](https://github.com/juliandescottes/piskel/blob/master/.travis.yml#L7) (maybe anything less than 1.1.0) being globally installed (dependency not listed in package.json) and it in turn depends on PhantomJS 1.9.2 (or anything less than 2.0.0) being in your PATH (it is in package.json, but not necessarily in the PATH).

It would be nice to update to the latest [casperjs (1.1.1)](https://www.npmjs.com/package/casperjs) and [phantomjs-prebuilt (2.1.7)](https://www.npmjs.com/package/phantomjs-prebuilt) npm packages and wire up the tests to depend on those executables instead of global ones, so that `npm install` provides all dependencies for the integration tests.

Unfortunately, CasperJS 1.1 [introduced lots of breaking changes in their API](https://github.com/casperjs/casperjs/releases/tag/1.1-beta1).  They've written [an upgrade guide](http://docs.casperjs.org/en/latest/upgrading/1.1.html).  It looks like a pain, but it's probably best to do it soon while the integration test suite is small.

I might get around to this as I get further into development on code-dot-org/piskel; if I do, I'll open a PR here.

**Comment by juliandescottes** [comment]
Thanks for the detailed suggestion! As you said, best to do it now since we only have to migrate:
- https://github.com/juliandescottes/piskel/blob/master/test/casperjs/DrawingTest.js
- https://github.com/juliandescottes/piskel/blob/master/test/casperjs/SmokeTest.js

> I might get around to this as I get further into development on code-dot-org/piskel; if I do, I'll open a PR here.

Since you are not working on this "right now", I might have a look this week end :)

**Comment by juliandescottes** [comment]
Fixed AFAICT.
