### ISSUE TITLE
Paste not working

### ISSUE THREAD

**Issue by bigtunacan** [juliandescottes/piskel#484]
Trying to copy/paste on the website from a Mac in the Chrome browser, but nothing happens.

**Comment by juliandescottes** [comment]
Can you give more details about your issue?

The copy/paste is not really intuitive, so I'll just add the steps here juste in case:
1 - choose a selection tool
2 - select an area on the screen 
3 - copy (ctrl+c) or cut (ctrl+x) (or cmd+c and cmd+x if on Mac)
4 - move your selection (don't switch tools, just click and drag the selected area, you should see the cursor change)
5 - paste (ctrl+v or cmd+v)

**Comment by bigtunacan** [comment]
@juliandescottes Ok; this apparently works correctly, it is just not what I was expecting.  Thanks.
