### ISSUE TITLE
Bigger than 32x32

### ISSUE THREAD

**Issue by Endertricity** [juliandescottes/piskel#486]
I may just be an idiot, but is there any way to create something bigger than 32x32? So far I really enjoy using piskel but what if I want to sprite something bigger?

**Comment by Ghokun** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3802058/16107049/4dbe0766-33a2-11e6-9e3e-744fe2dcc576.png)

**Comment by Endertricity** [comment]
thanks so much! I was wondering how to do it.
