### ISSUE TITLE
Export is not Lossless?

### ISSUE THREAD

**Issue by bitinn** [juliandescottes/piskel#496]
Seems like some semi-transparent dark pixels are lost or set to non-transparent when I import a spritesheet image and export them into individual frames. (Export as zip option).

Both import and export are PNGs. (see below image for a comparison between import sprite and export image).

![screen shot 2016-07-03 at 3 12 07 pm](https://cloud.githubusercontent.com/assets/1484279/16544240/d6bdc858-4130-11e6-857a-df0dd8cade62.png)

**Comment by bitinn** [comment]
Actually I have a feeling them are lost on *Import*, as we don't see those semi-transparent image in the preview window...

**Comment by juliandescottes** [comment]
Thanks for the report!

Alpha-channel (or semi-transparent) colors are not supported in Piskel. When you import an image containing such pixels, they are either made fully transparent or fully opaque (depending on their opacity).

I think we can close this as a duplicate of #434 . The only way to add transparency in Piskel for now is by using the alpha setting for each layer (but it globally applies to the whole layer).

**Comment by bitinn** [comment]
it's ok, as long as it's by design :)
