### ISSUE TITLE
Ghost Color

### ISSUE THREAD

**Issue by Willsm50** [juliandescottes/piskel#500]
![bug](https://cloud.githubusercontent.com/assets/20373335/16709375/6e968af4-4639-11e6-9209-d4fab98839e5.png)
Hi! Recently, I manage to create new color palletes. I've choose each color I want for my pixel art. but then, this happened, the color doesn't display on color palletes tab. If "Manage this pallete" button pressed, The app crashed.
![bug2](https://cloud.githubusercontent.com/assets/20373335/16709409/3a45e5be-463a-11e6-811b-5ec939eddec4.png)
Thats very much it, im glad if you could fix it.

**Comment by juliandescottes** [comment]
Hi,

Thanks for reporting the issue. I tried reproducing the problem, but didn't manage to so far.
Do you remember if you created your new palette from scratch or if you modified an exisiting palette?

To be safe I can still make the application catch the error you are getting when trying to edit the palette, but it would be nice to understand the root cause first.

**Comment by Willsm50** [comment]
I'm not sure, This pallete was made by cloning existing image. I got this bug with offline version. I've tried using this ghost color, it just mimic previous color. Might be corrupt saved pallete.
The only way I do to fix the pallete is by deleting saved folder at C:\Users\intel\AppData\Local\piskel

**Comment by juliandescottes** [comment]
> This pallete was made by cloning existing image 

@Willsm50  Could you share the image so that I can try and reproduce the issue?

**Comment by Willsm50** [comment]
Sorry, I don't have the image. What i mean with existing image is cloning existing image color, my bad. I think this bug happened with older version, I use ver 0.5.5.1 before. Didn't get any bug since updating to latest version. Already fixed by deleting local data.

**Comment by Willsm50** [comment]
Please Lock / Close this thread, i don't have any problem anymore :)

**Comment by juliandescottes** [comment]
Sure, thanks for updating!
