### ISSUE TITLE
Change tab title with Piskel name

### ISSUE THREAD

**Issue by epicabsol** [juliandescottes/piskel#505]
To reproduce, create a new Piskel and save it to your gallery with a different name. The browser tab text does not change to reflect the new name, and instead still shows the original name ("New piskel"). Instead, the tab text should change to reflect the new file name, or if this is not possible, the tab text should not include the file name.

**Comment by juliandescottes** [comment]
Good point! 

Updating the window's title should be handled by the website that embeds piskel. So here we actually think about piskelapp.com, for which the code is at https://github.com/juliandescottes/piskel-website

Ideally, piskel-website should have a script that does this and also takes care of what is currently handled in HeaderController.js. In the meantime however we could handle it in HeaderController.js directly, just making sure that window.pskl.appEngineToken_ is truthy (this token should only be set when piskel is embedded in piskel-website).

**Comment by juliandescottes** [comment]
Fixed, closing
