### ISSUE TITLE
Yellow Background after download and importing into Gamesalad

### ISSUE THREAD

**Issue by Obierunkenobie** [juliandescottes/piskel#523]
Hello, I was curious how I might eliminate the yellow background and make it transparent in Piskel. I am teaching a class and Piskel would be perfect for what I am doing....

Thanks

Obie
![knight](https://cloud.githubusercontent.com/assets/20978878/17606614/7048eb34-5fee-11e6-9af6-4e7ecc342e7e.gif)

After closer inspection, Gamesalad only works in 8-bit, Piskel is 16...  Thanks, I'll have to sort it out on the gamesalad end.

**Comment by epicabsol** [comment]
Piskel should not be adding any extra background to your sprites. Could you
upload a sample .piskel and .png that shows the problem?

>

**Comment by Obierunkenobie** [comment]
Hello my friend,


I found it to be an error onGamesalad's end. All is well. I love the Piskel
software. I'll most likely use it to teach my in my classroom this coming
school year.

Thanks

Clark

**Comment by juliandescottes** [comment]
Thanks for taking care of this @epicabsol and thanks for reporting back @Obierunkenobie  :) Closing.
