### ISSUE TITLE
Perfomance improvements

### ISSUE THREAD

**Issue by david-szabo97** [juliandescottes/piskel#528]
@juliandescottes 
I'm working on a performance improvement for Piskel and I was wondering what's the main reason for the 2nd level cache. As far as I see it only hits the cache when there are multiple calls for the same content. Though it seems a waste of resources because it takes a lot of CPU time to serialize that array.

The pull request I'm working on is using typed arrays and without 2nd level cache. Right now I can edit 1024x1024 files without any performance issue. Memory is hugely reduced when you are working with bigger files.

Reworked pixel storing implementation of Frame class to use Uint32Array typed arrays which means we can easily store RGBA in those. At rendering I'm using a Uint8ClampedArray view to serve it for .putImageData() which is way faster.

Right now every tests runs fine and had no problems when I was using it, I squashed every bug I found. :smile: 

-----
Done:

- New pixel map implementation (multi-dimensional rgba string array => uint32 typed array)
- pskl.utils.drawToCanvas and FramesheetRenderer reworked to take advantage of the new pixel map implementation (.putImageData())
- Micro optimization for pskl.utils.hashCode()
- Throttle Preview and Framelist renderer to 1 (?) render / second
- Backward compatibility
- Changed every JSON.stringify to .toString() for hashing

On-hold:

- ~~Remove level 2 cache from renderers~~
- ~~Micro optimization: replace "getContext('2d') with a custom "getContextCached('2d')" function, this performed 120ms vs 5ms on my PC in 1 million iteration. I will profile Piskel about this though with the new changes I think this micro optimization is useless.~~

WIP:

- ~~Change data format from JSON to binary (ArrayBuffer / Blob) (It's blazing fast! => write 5k vs 115k, read => 4k vs 2.5million), this could speed up the history service a lot.~~
- ~~Fix ColorsWorker to work with the new pixel map and color calculation.~~

I'll open a pull request sometime in the next few days, just posted here for incidental discussion.

**Comment by juliandescottes** [comment]
That sounds extremely promising, I really can't wait to try your PR :)

> I'm working on a performance improvement for Piskel and I was wondering what's the main reason for the 2nd level cache

"If I remember correctly", the second level cache was added to improve the performance when deleting a frame or moving a frame on sprites with a lot of frames (20+). Of course it's based on the assumption that serialization was still faster than drawing the frame. This was the case when I implemented it, but maybe this no longer holds?

> Right now I can edit 1024x1024 files without any performance issue. 

For reference, when asked what kind of sprites one could work on with Piskel, I usually gave this list :
- below 50x50 : as many frames as you want
- between 50x50 and 100x100 : animations up to 100 frames
- between 100x100 and 200x200 : animations up to 20 frames
- over 200x200 : single frames

It would be interesting to take the opportunity here to update this and actually post it somewhere. 

We could also create reference sprites representing the different categories we hope to support, that we could reuse for testing. That will also make reviewing performance changes easier, if we can have this set of sprites that "should work".

> Throttle Preview and Framelist renderer to 1 (?) render / second

As you realized, rendering these two elements should not be on the critical path most of the time. Throttling should effectively already the situation. In the long run, I would love to have them offloaded to a webworker, to avoid blocking the main thread.

> Rework the whole frame render system to work in chunks (like 256x256 or 128x128 chunks, though this is very low priority)

I was actually wondering if swapping the canvas 2d for webgl could improve the situation here? Thoughts?

Thanks!

**Comment by david-szabo97** [comment]
> For reference, when asked what kind of sprites one could work on with Piskel, I usually gave this list :
below 50x50 : as many frames as you want
between 50x50 and 100x100 : animations up to 100 frames
between 100x100 and 200x200 : animations up to 20 frames
over 200x200 : single frames

I found myself drawing whole screens to see my game in one piece thus a 640x360 is a bare minimum for me. Though the lack of importing of another piskel made this hard for me, looking to implement that too after the optimization.

> As you realized, rendering these two elements should not be on the critical path most of the time. Throttling should effectively already the situation. In the long run, I would love to have them offloaded to a webworker, to avoid blocking the main thread.

Yes, I was trying to offload them though they are using the CachedFrameRenderer right now so I've chosen the easier path for now. Will look into later though.

> I was actually wondering if swapping the canvas 2d for webgl could improve the situation here? Thoughts?

I totally forgot about WebGL :smile: That would make rendering blazing fast, putting this on top of my list.

**Comment by juliandescottes** [comment]
PR merged. Closing.
