### ISSUE TITLE
Load image from server disk

### ISSUE THREAD

**Issue by josuperstar** [juliandescottes/piskel#544]
Hi !
How could we load a default sprite, as it is the case with the megaman sprite on http://www.piskelapp.com/ , which would be stored on the server side ?

**Comment by juliandescottes** [comment]
Hi. Not sure I understand the request here. If you have an account on piskelapp.com, you can save sprites to your gallery and they are saved on the server.

**Comment by josuperstar** [comment]
I would like to use the code on a personal project where I already have sprites on a server. I would like to edit and create new sprite using piskel API.

**Comment by faabiopontes** [comment]
On the right side of the screen you can click on the Import button (symbol is a folder).
![image](https://cloud.githubusercontent.com/assets/2223935/19029597/07802906-891e-11e6-8e9f-73145cec8328.png)

Then you just import the files from your computer.

You might have to move the files from your server to the computer, and they have to be in the format PNG, JPG, BMP or GIF!

**Comment by josuperstar** [comment]
Thanks,
I see how I can open files from my computer. My question was more about the API.
For example, in app.js, we have:
layer.addFrame(frame);

I was wondering if it's possible to do something like this:
layer.OpenFile(FilePathOnServer);

**Comment by josuperstar** [comment]
As I said earlier, the goal is to be able to do the same thing than the website  http://www.piskelapp.com/ where it opens a megaman sprite on the load up.

**Comment by juliandescottes** [comment]
So the way it works on piskelapp is that the page contains a serialized sprite and when app.js boots up it deserializes the sprite and loads it in the application, which is probably not what you need here.

Without having more information about the way you embed/use piskel and the format in which your sprites are saved, it's hard to know what would be useful to you here exactly.

The following code snippet is a good example of what needs to be done to load a sprite if it was previously saved/serialized by Piskel.
```javascript
    // getSerializedSpriteFromServer is for you to figure out
    var serializedPiskel = getSerializedSpriteFromServer(path);

    pskl.utils.serialization.Deserializer.deserialize(serializedPiskel, function (piskel, extra) {
      pskl.app.piskelController.setPiskel(piskel);
      pskl.app.previewController.setFPS(extra.fps);
    });
```

Now I don't know in which format the sprites are stored on your server. You might have to convert them to something Piskel can process. If there are image spritesheets, have a look at the ImportService, it might help.

**Comment by josuperstar** [comment]
Hi !
Thanks for your awnser.
I was thinking to use the piskel format, as I want to eventually save modifications.
I'll take a look at this ! Thanks !

**Comment by juliandescottes** [comment]
No problem, glad to help! 
One last comment, the code snippet I pasted is based on the last version of Piskel. If your fork is a bit old you might have to re-synchronize (we used to have to set the descriptor, but it's now handled by Deserializer.deserialize

**Comment by juliandescottes** [comment]
Closing for now.
