### ISSUE TITLE
Piskel Background Transparency Not Working

### ISSUE THREAD

**Issue by Csyrian** [juliandescottes/piskel#547]
I import a picture with a transparent background, animate it in Piskel, export it and the transparent background turns white. 

This is my first time experiencing this and I've used Piskel multiple times prior with no issue.

Here's the animation: http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgID22vqjCww/view

But when I downloaded it and uploaded it to another site (deviantart), the background turns white: http://sta.sh/01kks0nvt9v4

I need to get this commission fixed soon. I hope this can be resolved. 

Thanks!
  -Chris

**Comment by epicabsol** [comment]
I reproduced the issue. In the meantime, you could use GIMP to edit the gif to get output like the following:
![hannahrhurstfloatchibicommission clone fixed](https://cloud.githubusercontent.com/assets/4462127/18575265/7bed05ee-7b8a-11e6-8525-3077e7f3025b.gif)

**Comment by juliandescottes** [comment]
Thanks for taking a look @epicabsol !

This sprite has ~1400 different colors, and I had to disable transparency in GIF exports for sprites that have more than 256 colors. (see issues #357 and #358)

The only workaround at the moment is to do what @epicabsol suggested.

I think we have a few options to improve this though:
- display an error message when exporting a sprite with transparent pixels & more than 256 colors (with link to a wikipage explaining the issue, workarounds etc...) 
- let the user choose to keep transparency, even if it might screw up the output (with a checkbox in the export controller?)
- perform a color reduction on our side before sending the sprite to gif.js, and submit 256 colors (including the transparent color)

**Comment by Csyrian** [comment]
Thanks so much! :'D The quick fix and immediate responses are really great. ♥
