### ISSUE TITLE
wont load page 

### ISSUE THREAD

**Issue by Jamessssssssss** [juliandescottes/piskel#549]
i resize page all the way up and it wont load now

**Comment by juliandescottes** [comment]
@Jamessssssssss , we need more details to investigate here.
- which page are you talking about (url?)
- what do you mean by "resize"? Did you:
  - resize your browser window? 
  - use the resize tool in Piskel?

Can you describe the steps you did before this issue occurred?
A screenshot of the current state ("wont load now") would also be great to understand what you're talking about.

Thanks!

**Comment by juliandescottes** [comment]
No answer from logger and not actionable as it is. Closing the issue.
