### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by Homocircuit** [juliandescottes/piskel#551]

**Comment by juliandescottes** [comment]
@Homocircuit can you provide more details that lead to this?

**Comment by juliandescottes** [comment]
Is http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgIDOu8nRCgw the sprite you are trying to save ? I am seeing a spike of errors in the logs of piskelapp.com for this id.

Any chance you could download it as a ".piskel" file and either attach it here or send it to me by email? 

![image](https://cloud.githubusercontent.com/assets/1141550/19040245/992f0a9c-8983-11e6-92fe-1181a452dc54.png)

**Comment by Homocircuit** [comment]
I have tried importing it, although the issue just repeats and it erases
itself from existence.

However, if it is helpful, here is the piskel file

**Comment by juliandescottes** [comment]
@Homocircuit looks like you can't attach it on github, could you send it by email?
Thanks.

**Comment by juliandescottes** [comment]
@Homocircuit ping. Haven't received anything yet :(

**Comment by juliandescottes** [comment]
No response, closing for now.
