### ISSUE TITLE
[Safari] Zooming in/out breaks the drawing area

### ISSUE THREAD

**Issue by Garblesome** [juliandescottes/piskel#554]
Hello, this has been a reoccurring issue for me for the last few days, and I had assumed it had stopped but it seems to have come back up again. Occasionally, whenever I am attempting to access a tool through a keyboard shortcut, or even click on the drawing area, it goes all gray, as if I used the paint bucket tool on it in an attempt to create a gray background. I am still able to switch to other tools of course, and the rest of my screen is intact, so I know it is not an issue with my computer. I am still also usually able to see the smaller preview screen to the top right, but the drawing area is completely gray, and when I attempt to draw using the smaller screen, nothing is registered, and it does not change at all. When I duplicate the frame I am on in attempt to preserve my creation, the drawing area is still completely gray and unresponsive. This has happened to me four times now, the first three times were when I was attempting to undo an error with Command Z, and the last time I had simply clicked on the drawing area with

UPDATE: I took a screenshot as well
![screen shot 2016-10-09 at 8 29 59 pm](https://cloud.githubusercontent.com/assets/22734661/19225168/3f4216d8-8e64-11e6-9697-21c6231ca4e8.png)

**Comment by juliandescottes** [comment]
Thanks for the screenshot. This is the first time this issue gets reported as far as I know. 
I see you are using Safari here, and I don't really test against safari so maybe a Safari only issue?

I see you also have Firefox installed. Could you try with this browser and report back if you have the same issue? In the meantime I'll try to manual test a bit on Safari.

**Comment by juliandescottes** [comment]
Ah looks like this happens pretty frequently on Safari. At least I could trigger it by zooming in / out. 
I'll try to have a look, in the meantime I would advise using either Firefox or Chrome.

**Comment by juliandescottes** [comment]
Will be released with Piskel v0.9, which should be up in the coming days.

**Comment by Garblesome** [comment]
Yes, this seems to be a Safari-specific problem. I have switched to Firefox, and it seems to run seamlessly so far. Thank you very much for your help on the matter. I await Piskel v0.9 then.
