### ISSUE TITLE
Display a warning message when using big resolution

### ISSUE THREAD

**Issue by MrAMultimedia** [juliandescottes/piskel#555]
Hi there,

I am a middle school teacher using this program in my multimedia class. Every account except one is perfect. The one that is not cannot save a project with any of the three options if it's over 50 frames. Is anyone else having this issue?

Thank!,
Mr. A

**Comment by juliandescottes** [comment]
Hi!

Other than the number of frames, the number of layers, the resolution and the complexity of the sprite all contribute to the final size of the animation. If it gets over 1MB saving on your account will fail. I'm quite surprised the other methods are failing though.

Could you let me know the number of layers and resolution of your animation? Also when you say it fails, how does it fail exactly for each method. For what it's worth, I consider the ".piskel" file download to be the less likely to fail here.

**Comment by juliandescottes** [comment]
@MrAMultimedia can you provide the requested information? Otherwise this issue will be closed.

**Comment by MrAMultimedia** [comment]
Hi,

Sorry about the late reply. Thanks so much for your quick response, The student in question was using the largest dimensions and going over 50 frames, just 1 layer. Didn't have a chance to check, but I imagine that would go over the 1MB. He has since moved to a smaller resolution. I would need to check but am fairly certain that the .piskel file was not functioning either. I remmeber trying out that option and while a file would save, there would be nothing in it (0kb).

Thanks,    
Mr. A

**Comment by juliandescottes** [comment]
Thanks! 

That's another case where a warning should be displayed when using a too big resolution :( 
I don't think I have an issue dedicated to improving this yet, so let's use this one.

**Comment by juliandescottes** [comment]
We now display warnings when performance issues are spotted.
