### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by supervg123** [juliandescottes/piskel#558]
It crashes... a lot... especially when I open it. Before it does, I can't edit anything. The screen just comes up in dark grey. Nothing can be done, except for the right bar, but nothing else. Help?

**Comment by Tranberry** [comment]
If I was you, I'd tell us what OS and if you are using the stand alone program or not, and if not I'd also include what browser I used.

**Comment by juliandescottes** [comment]
Thanks for replying @Tranberry ! 

On top of that, if you happened to use Safari on OSX there is an issue that turns the drawing area grey when using the mousewheel. I just updated the version released on piskelapp.com to include only this fix.

**Comment by juliandescottes** [comment]
No information from logger, closing.
