### ISSUE TITLE
Layer name text wrapping disrupts layer list

### ISSUE THREAD

**Issue by epicabsol** [juliandescottes/piskel#559]
To reproduce, start a new piskel and create a new layer. Name it something long with spaces. Ensure that the top layer with the long name is selected. 
Observed behavior: The long layer name will wrap to the next line in the layer list, showing behind.
![screenshot 2016-10-25 at 2 33 39 pm](https://cloud.githubusercontent.com/assets/4462127/19705217/16e1ad4e-9ac0-11e6-8119-4caeb9d7a51c.png)
Additionally, if there is a word without spaces in the layer title, the layers list will grow horizontally.
![screenshot 2016-10-25 at 2 35 23 pm](https://cloud.githubusercontent.com/assets/4462127/19705296/8f88136e-9ac0-11e6-8014-cf8551984c97.png)

Expected behavior: The long layer name is truncated, perhaps with an ellipsis, or the layer list item grows vertically, but doesn't overwrite the next layer title.

**Comment by juliandescottes** [comment]
Thanks for the report @epicabsol !

**Comment by GMartigny** [comment]
@juliandescottes What's prefered : Elipsis or vertical grow ?

**Comment by juliandescottes** [comment]
@GMartigny I think we should go for an ellipsis, and make sure that the title attribute is properly set with the name of the layer.

**Comment by juliandescottes** [comment]
Fixed by @GMartigny
