### ISSUE TITLE
Bigger canvas size? [Feature request]

### ISSUE THREAD

**Issue by hassanshaikley** [juliandescottes/piskel#562]
Are bigger canvas sizes going to be supported?

Right now it's 100x100, I think. Will we allow something like 500x500

Thanks : )

**Comment by juliandescottes** [comment]
I might be missing the point, but you can resize your drawing canvas using the resize panel:

![image](https://cloud.githubusercontent.com/assets/1141550/20412069/da880aa6-ad24-11e6-842e-11d4a4c57715.png)

There's no hardcoded limit, but keep in mind Piskel was designed to edit small sprites.
Feel free to reopen if this doesn't answer your question!
