### ISSUE TITLE
Color preference. [Enhancement Request]

### ISSUE THREAD

**Issue by JFC263** [juliandescottes/piskel#563]
Hey I don't have any idea on how to use github but i love piskel and i would love if there would be a tiny feature in where you can choose in the settings which color type you rather use like RGB or #. Thats it.

Thank you for listening. @juliandescottes @grosbouddha

**Comment by epicabsol** [comment]
I agree, although in the meantime, you can type 'rgb(r, g, b)' into the color entry textbox (or named colors, like 'sienna').

**Comment by JFC263** [comment]
> I agree, although in the meantime, you can type 'rgb(r, g, b)' into the color entry textbox (or named colors, like 'sienna').<

Yes, but it still goes back to the other type of color and that cost effiency and time.

**Comment by juliandescottes** [comment]
I had a quick look at what would be needed to suport this. I assume we are only talking about having changing the value displayed in the input of the colorpicker widget. This widget is a modified version of https://github.com/bgrins/spectrum . It supports a 'preferredFormat' configuration option. However, when setting this to 'hex', the transparent color becomes unselectable.

The spectrum widget used by piskel already has a substantial amounts of piskel specific modifications, so there is no easy upgrade path here. 

We could keep modifying the spectrum,js file though. The idea here would be to add an 'preferredInputFormat' configuration option to the widget and control this from an additional entry in the application settings panel.

The files to modify here would be:
- src/js/controller/settings/ApplicationSettingsController.js : add a select to pick the preferred color format
- src/js/utils/UserSettings.js : add a new user setting entry (e.g. COLOR_FORMAT)
- src/js/controller/PaletteController.js : listen to user settings changes (see other files listening to Events.USER_SETTINGS_CHANGED as a reference)
- src/js/lib/spectrum/spectrum.js (see https://github.com/juliandescottes/piskel/blob/master/src/js/lib/spectrum/spectrum.js#L674)

I can go into more details if anyone wants to pick this up.

**Comment by JFC263** [comment]
>I had a quick look at what would be needed to suport this. I assume we are only talking about having changing the value displayed in the input of the colorpicker widget. 

Yes actually is just that.
