### ISSUE TITLE
Color Picker on bottom left should display color in Hex format

### ISSUE THREAD

**Issue by mattnv92** [juliandescottes/piskel#565]
Since palettes are not saved from one browser to the next, I often find myself eye dropping colors on the page to recreate a palette. The color picker on the left side of the page shouldn't display the color in RGB( r, g, b) form, because it is not copy paste friendly. 

![piskelproblem](https://cloud.githubusercontent.com/assets/3315927/20458362/e730c528-ae68-11e6-8be3-bfd7eac892bf.png)

**Comment by C0deAMet** [comment]
That's true

**Comment by JFC263** [comment]
I made an issue that it just should be a prefference in options to choose what color format you want to use

**Comment by juliandescottes** [comment]
Thanks for the report. As mentioned by @JFC263 , this issue and #563 are almost identical so I'll close this one as duplicate.
