### ISSUE TITLE
http://localhost:8999, Line: 94, Column: 5 Invalid Character

### ISSUE THREAD

**Issue by tx350z** [juliandescottes/piskel#571]
Downloaded and extracted zip. Copied all folders/files from piskel-master/piskel-master to document root.

Hangs with :Loading Piskel..." Same problem using Firefox 50.0 and IE 11.0.9600. Running on XAMPP for Windows 5.6.15.

Error is on the @@include line in index.html.
```
  <script type="text/javascript">
    @@include('piskel-boot.js', {})
  </script>

```

**Comment by juliandescottes** [comment]
@tx350z you can follow the instructions at https://github.com/juliandescottes/piskel/wiki/Development-Environment ! 

Thanks.
