### ISSUE TITLE
Can't Save 

### ISSUE THREAD

**Issue by zxluker** [juliandescottes/piskel#575]
I don't know why but once i hit about 40 frames on a Gif or about 8 layers is starts to glitch and not be able to save, is there anything I can do to fix this? 

PS: Would appreciate if u added and flip tool (aka) horizontal flip or  diagonal flip.

**Comment by juliandescottes** [comment]
Hi, thanks for reporting the issue. Could you give more details:
- what is the size of your sprite ? 
- how many frames and layers are you using ? 
- how are you trying to save it (online gallery, local browser, download as piskel file, export to image...)

Also relevant:
- what is your browser ?
- what are the specs of your machine ?

> starts to glitch
What do you mean by this? Do you see / have issues in your sprite before trying to save? Please be as explicit as possible.

If your sprite is too big, then there's not much you can do at the moment, sorry. There are hard limits on what I can store online. GIF export should behave better than most of the other export tools, but depending on the size of your sprite it might become buggy too.

I am adding warnings in #555 to let users know when they start to exceed what the program can handle. 
I can fix improve the .piskel save to store bigger sprites that it does today.  

> PS: Would appreciate if u added and flip tool (aka) horizontal flip or diagonal flip

The flip tool performs a vertical flip if you hold alt when clicking on the tool. 
![image](https://cloud.githubusercontent.com/assets/1141550/20661106/3bfd714c-b54d-11e6-88c2-411884393e98.png)

**Comment by juliandescottes** [comment]
No answer from logger. Closing
