### ISSUE TITLE
Multi-Imports [Enhancement request]

### ISSUE THREAD

**Issue by JFC263** [juliandescottes/piskel#578]
I *NEED* this feature to make variations and resprites, I know it could be difficult to make every import make a new frame but it would be a GOLDEN tool.

**Comment by juliandescottes** [comment]
@JFC263 Thanks for logging, can you provide more details about your feature request?
Is it about importing an existing image/sprite without overriding the current animation? 

There are already several issues opened about this: #285 and #294 .
Can you check them if they already cover what you want here?

**Comment by JFC263** [comment]
I read all of them ( #284  , #285  and #294 ) and yes is just what you said

> @JFC263 Thanks for logging, can you provide more details about your feature request?
**Is it about importing an existing image/sprite without overriding the current animation?**

It surprised me that it is possible to actually import multiple files but you need to make it more open and intuitive to others because i just discovered this feature by reading those posts, make it to work without the need of Drag 'n' Drop (DnD) because people would think that dragging and dropping does the same effect as importing with the proper button but it doesn't it totally works with drag 'n' drop.

BTW: It looks like the canvas size doesn't matter with drag and drop it will just end up getting cutted.

PS: To make DnD to work you need to import a first file to set the canvas size or just do it manually, this works when you are spriting variants/recolors.

**Comment by JFC263** [comment]
Update: I noticed that importing two things at once only loads the first frame and it doesn't matter if it is a spritesheet with the same dimensions or a gif.

**Comment by juliandescottes** [comment]
@JFC263 the only way to import without overriding is the one you described, to drag and drop an image. It is obscure and hard to find, that's why we need a better import feature, that handles multiple files properly :)

My point was just that if we already have other issues tracking this we could maybe close this one to avoid duplicates. 

Let's move the conversation to issue #285 please.
