### ISSUE TITLE
Redo button

### ISSUE THREAD

**Issue by JFC263** [juliandescottes/piskel#583]
Sometimes i just press the wrong button or I undo because I do not remember what have I done and then I can't redo. Well it is just that.

**Comment by juliandescottes** [comment]
The redo shortcut should be CTRL / CMD + Y (or SHIFT + CTRL / CMD + Z)

Is that what you were looking after?

**Comment by JFC263** [comment]
Much better thanks, and great use of shift for an opposite effect.

I consider this, CASE CLOSED!!!
(Without any: OBJECTION!!!)
