### ISSUE TITLE
I cant save something to my gallery.

### ISSUE THREAD

**Issue by VioletRubyRose** [juliandescottes/piskel#585]
i tried to save a 500 x 180 piskel and it didn't work. why?
 
This is it:
![sxyndscrndnc](https://cloud.githubusercontent.com/assets/24513495/21084460/afef30be-bfc9-11e6-94e2-eaa18d2161b6.gif)

plz help

**Comment by juliandescottes** [comment]
Sorry about that. 

There is a limit of 1MB on what can I can store online. From the looks of it your gif is too big to fit the limit. I am adding warnings in the next version to notify users about this kind of limitations. 

Try maybe to download it as a .piskel file as an alternative.

**Comment by juliandescottes** [comment]
Working on this in #594
