### ISSUE TITLE
Piskel desktop app freezing on mac

### ISSUE THREAD

**Issue by Aerotune** [juliandescottes/piskel#597]
I experience the piskel desktop app freezing quite a lot on mac so I have to force quit it. I haven't seen it happen with a specific tool so I'm not sure how to reproduce it since it simply happens while animating.

### Steps to reproduce the bug
1. Open existing piskel from the website in the desktop app
2. Draw/flip/move/create new frames
3. ???
4. Program is frozen

I couldn't find anything that might be related in the console.

### Environment details
OS X 10.11.5 and piskel-0.8.0 desktop app for mac.
A MacBook pro with a retina display if that matters.

### Sprite details
* number of frames: 2 - 10
* sprite resolution: 32x32
* session duration: 2 - 15 min (before freezing)

[piskels.zip](https://github.com/juliandescottes/piskel/files/672196/piskels.zip)

I'm really happy with Piskel in general and I just wrote a parser for Love2D so I can draw the .piskel files directly in my game. With the offline version the workflow becomes pretty easy and efficient.

**Comment by Aerotune** [comment]
Update: OK I'm having no problems with piskel-0.6.0 so I'm using that version for now.

**Comment by papernoise** [comment]
Same problem here. I'm running v.0.8.0 on Yosemite (10.10.3) and get freezes when:

-  using the colour picker (usually it's fine if I click on the selector and drag, but it freezes when I just click on the spot where the colour I want sits.)
- with a project of more than one frame. There it will always freeze after a couple of minutes.

the program doesn't really freeze, just the UI does. You can quit it normally (no need to force quit), but clicking on any UI element won't do anything.

**Comment by papernoise** [comment]
I just saw that there's a new version... will give it a try, though there's no mention of a fix for this in the changelog.

**Comment by juliandescottes** [comment]
Thank you both for the detailed reports. I haven't been able to reproduce crashes on OSX (10.11.6) using 0.8.0 so far :(

The issue can either be linked to a bug in piskel (but I think you would see an error message in the UI in this case) or to an issue with the tool (nw.js) I use to bundle it as a desktop application. A new version of this tool was released and seems to have better performances. It might be worth trying to release a new version of Piskel using this.

I will upload a new build using nw.js 0.19.3, if you can try it out and let me know if it performs better for you that would be great.

**Comment by juliandescottes** [comment]
Uploaded at : https://drive.google.com/uc?export=download&id=0BwPjxqZA0YlRVE1NUGhsR1hhaEk

**Comment by papernoise** [comment]
Did some more testing... and it all seems to work fine with the latest version!
I've made this btw: http://www.papernoise.net/temp/fauci-newyear-big.gif

**Comment by juliandescottes** [comment]
@papernoise Thank you so much for testing! 

(and happy new year :) )

**Comment by Aerotune** [comment]
I just gave the new version a go and I'm not having any problems either. Thank you!
