### ISSUE TITLE
The first pixel is shown as 0:0 ...

### ISSUE THREAD

**Issue by TALANTO** [juliandescottes/piskel#604]
It counts one less:
![screenshot from 2016-12-29 14-06-15](https://cloud.githubusercontent.com/assets/16134110/21545506/36bbbe50-cdd0-11e6-8ee1-fea31d00b0fa.png)
1:1 is 0:0
32:32 is 31:31 but the image is 32 pixels wide.

**Comment by juliandescottes** [comment]
Thanks!

This would have to be changed in CursorCoordinatesController::redraw.

It should only be changed for display purposes. The actual coordinates & origin members of CursorCoordinatesController should keep starting at 0.

Before implementing this however, I'd like to check if other programs are starting at 0 or 1 (paint.net for instance?)  

@TALANTO if you have photoshop/paint.net or any other software, could you check if they work as you mention here?

**Comment by TALANTO** [comment]
Ok, it's my fault. Gimp shows 0, 0 and Paint.NET shows 0, 0.
I think that the Game Maker's build in editor is what confused me (but I can't test it right now).

**Comment by TALANTO** [comment]
I am completely wrong. Game Maker also starts from 0, 0. I am sorry can you delete this this issue?

**Comment by juliandescottes** [comment]
@TALANTO sure ! 

I don't feel strongly either way but it's good to know that other software are also using 0,0. Thanks for looking it up.
