### ISSUE TITLE
Copy & Paste doesn't seem to work

### ISSUE THREAD

**Issue by jeremyfa** [juliandescottes/piskel#610]
It seems that copy and paste doesn't work properly. I don't know if this is a macOS-only issue or not. Details below:

### Steps to reproduce the bug
1. go to piskelapp.com
2. select the pen tool
3. draw something
4. select the rectangle selection tool
5. select the pixels drawn with pen tool
6. press CMD + C
7. select another area with rectangle selection tool
8. press CMD + V
9. **nothing happens, while we would expect the copied pixels to be pasted**

### Environment details
* operating system: macOS Sierra
* browser: reproduced on latest Google Chrome and latest Firefox

**Comment by juliandescottes** [comment]
Hi!

Copy paste is a bit counter intuitive in Piskel. 
You should not clear your selection after doing cmd + c. See https://github.com/juliandescottes/piskel/issues/484#issuecomment-226008500

Let me know if this works for you.

**Comment by jeremyfa** [comment]
Oh I see. That's indeed a bit counter intuitive, but, well, it works!

**Comment by jeremyfa** [comment]
(and thanks for the quick feedback!)

**Comment by solidifies** [comment]
hey! the github link was removed! Help!

**Comment by juliandescottes** [comment]
Ah indeed, the issue moved to another repo:

https://github.com/piskelapp/piskel/issues/484#issuecomment-226008500

@solidifies
