### ISSUE TITLE
macOS desktop version freezes

### ISSUE THREAD

**Issue by jayce-leathers** [juliandescottes/piskel#612]
Bug description

(this template is intended for bug reports, erase it when requesting features/enhancements)

### Steps to reproduce the bug
1. open piskel desktop app
2. use for awhile
3. it freezes and becomes totally unresponsive
### Environment details
* operating system: macOS Sierra 10.12.2 on mid 2015 Macbook Pro 15'
* browser (or offline application version): 0.8.0

### Sprite details
* number of frames: 4
* sprite resolution: 128
* session duration: ~5 - 15 min

I'm not sure what's causing the freeze. It seems to happen after a period of time no matter what I'm doing. Is there any sort of logging built into the application? I'm a developer myself and use this program to teach kids how to code videogames. I'm willing to work on a solution I just need someone to point me in the right direction.

**Comment by juliandescottes** [comment]
Can you give a try to https://drive.google.com/uc?export=download&id=0BwPjxqZA0YlRVE1NUGhsR1hhaEk (0.10.0 beta)

Seems to work for others who reported similar issues

**Comment by juliandescottes** [comment]
As 0.10.0 was released, closing.

**Comment by jayce-leathers** [comment]
Sorry I forgot to report back. It was fixed in 0.10.0 👍
