### ISSUE TITLE
GIF export fails if image contains more than 256 colors

### ISSUE THREAD

**Issue by juliandescottes** [juliandescottes/piskel#621]
STRs:

- Import the following image in piskel:
![image](https://cloud.githubusercontent.com/assets/1141550/22250347/d8a3ffea-e246-11e6-989c-323de4dceb8c.png)

- export as GIF

The export fails and generates an invalid GIF.

[CurrentColorsService::getColors](https://github.com/juliandescottes/piskel/blob/fbaccb03f215b7739eb2585ae308c338c3aec8c3/src/js/service/CurrentColorsService.js#L26-L28) always returns an array of colors limited to the 100 colors displayed in the UI for the current colors palette. But here we need to know if the image contains more than 256 colors or not, as it changes the way we generate the GIF in [GifExportController](https://github.com/juliandescottes/piskel/blob/fbaccb03f215b7739eb2585ae308c338c3aec8c3/src/js/controller/settings/exportimage/GifExportController.js)

**Comment by bbaliguet** [comment]
Very beautiful piece of art ! 👍
