### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by GrugBe** [juliandescottes/piskel#623]
a little feature request :
is it possible to have an **Option + click** shortcut to acces the Color Picker ?
it's in a lot off graphic apps, and a conditioned reflex. ;)

**Comment by juliandescottes** [comment]
Why not! The only issue I can see at the moment is that the Move tool is using the option/alt modifier for a rather obscure feature.

I guess we could make this behaviour work for any tool except the Move tool (you usually don't need to pick colors if you are just moving the frame content ?).

For the record, the color picker is also available when using the mousewheel button (even thought it's not documented anywhere).
