### ISSUE TITLE
Can't import an image in an existing sprite

### ISSUE THREAD

**Issue by TheOtherCyrus** [juliandescottes/piskel#632]
The first one does almost nothing but may be related to another because they both used to not happen around the same time. 

### Steps to reproduce the bug
1. go to piskelapp.com
2. import an image
3. copy part of the image onto another frame

### Environment details
* operating system: Windows
* browser (or offline application version): Google and Bing

### Sprite details
* number of frames: any
* sprite resolution: any
* session duration: any

---------------------------------Second---------------------------------

Whenever I try to drag & drop an image the browser tab refreshes automatically. This means I can only import a single image because the import tool can't add to existing sprites. 

### Steps to reproduce the bug
1. go to piskelapp.com
2. drag an image file over the browser

### Environment details
* operating system: Windows
* browser (or offline application version): Google and Bing

### Sprite details
* number of frames: these are all consistent for me
* sprite resolution: any
* session duration: any

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.

**Comment by juliandescottes** [comment]
Thanks for filing. 

The copy/paste is not really intuitive but normally works, so I'll just add the steps here:
1 - choose a selection tool
2 - select an area on the screen
3 - copy (ctrl+c) or cut (ctrl+x) (or cmd+c and cmd+x if on Mac)
4 - move your selection (don't switch tools, just click and drag the selected area, you should see the cursor change)
5 - paste (ctrl+v or cmd+v)

> Whenever I try to drag & drop an image the browser tab refreshes automatically. This means I can only import a single image because the import tool can't add to existing sprites.

Drag and dropping images in Piskel should also add them to your sprite, provided your sprite size is big enough to contain them. Make sure your sprite resolution is bigger than the image resolution before trying to drag and drop any image.

Also a small precision, but you have to drop the image in the Piskel user interface. If you drag and drop the image on the actual browser tab, the tab will be reloaded and I can't do much about that.

When you say "Google and Bing", do you mean the search engines? I need to know the actual browser used: on Windows it's usually either Chrome, Firefox, Edge or Internet Explorer.

**Comment by TheOtherCyrus** [comment]
Thanks for the help! Turns out this is a problem with my browser for the
record.

**Comment by juliandescottes** [comment]
Thanks for the follow-up @TheOtherCyrus ! Closing.
