### ISSUE TITLE
Cross site scripting (XSS) bug in Image upload

### ISSUE THREAD

**Issue by P4P4Bless** [juliandescottes/piskel#641]
An XSS can be triggered if the user uploaded an image with an XSS vector as the file name.
![screenshot from 2017-02-23 16 31 28](https://cloud.githubusercontent.com/assets/25985606/23268445/b0e63b9c-f9e5-11e6-90b4-2d759cf9d9c1.png)

### Steps to reproduce the bug
1. Change Your image name , see the screenshot "Using xss payload as the name" 
![screenshot from 2017-02-23 16 36 46](https://cloud.githubusercontent.com/assets/25985606/23268708/711a72f2-f9e6-11e6-94d3-b3170bc8609c.png)

2. Go to http://www.piskelapp.com/p/create
2. Click on import and then browse images and select your image 
3. Voila XSS triggered 😄 

### Environment details
Linux Os
Firefox Browser

You can simply stop reflecting the file name into the page, it's not needed anyways. 👍

**Comment by juliandescottes** [comment]
Thanks for the report and great point! 

Looks like we have a similar issue if you use it as your sprite name when saving to your gallery.
For reference here's your example string to use for testing. 
```
><img src=x onerror=prompt(1)>
```

**Comment by P4P4Bless** [comment]
Yeah the Same problem and you're most welcome

**Comment by juliandescottes** [comment]
The main issue should now be fixed (still needs to be released to piskelapp.com however).
