### ISSUE TITLE
Feature Request : Ask Saving before exit

### ISSUE THREAD

**Issue by unins** [juliandescottes/piskel#659]
I sometimes forgot to save before exiting app. it will be comfortable if it asks me "Save before Exit?"

**Comment by juliandescottes** [comment]
I need to check but I think I fixed it recently (https://github.com/juliandescottes/piskel/pull/638)

This should be released with Piskel 0.11.0 (which should be coming soon, even if I don't have a lot of new features in it)

**Comment by juliandescottes** [comment]
I just tried the new desktop apps for v0.11.0 and the feature is indeed implemented.

Should be released this weekend. Closing.
