### ISSUE TITLE
No picture

### ISSUE THREAD

**Issue by deraj-nagar** [juliandescottes/piskel#671]
#Whenever I zoom in a little to get better detail on my project, the editing screen goes grey. If I zoom in a little, I can see the pixel grid if it is on, but when I do something, it disappears and I can only view the edits when zoomed out.

Steps to reproduce the bug
1. go to piskelapp.com
2.  Start zooming in.
3. When screen goes grey, select any tool that draws/paints.
4. Draw/paint something.

### Environment details
* operating system: ChromeOS
* browser (or offline application version): Chrome

### Sprite details
* number of frames: 1
* sprite resolution: 360*360
* session duration: not that long

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.
![screenshot 2017-05-01 at 5 17 42 pm](https://cloud.githubusercontent.com/assets/28279650/25599594/46a56384-2e92-11e7-9235-d5b72f30f357.png)
![screenshot 2017-05-01 at 5 17 51 pm](https://cloud.githubusercontent.com/assets/28279650/25599597/4ccd04f6-2e92-11e7-85dc-6dfd09b9fe73.png)
![screenshot 2017-05-01 at 5 17 59 pm](https://cloud.githubusercontent.com/assets/28279650/25599600/4fdacb42-2e92-11e7-955e-b898feadc75a.png)

**Comment by juliandescottes** [comment]
Hi, thanks for logging!

Unfortunately this is the same issue as #651 . 
It happens only on chromebooks and I don't own one so I can't investigate this at the moment :( 

I am closing this one as a duplicate, let's continue the discussion in #651
