### ISSUE TITLE
Zooming In Issue

### ISSUE THREAD

**Issue by Elven-Lord** [juliandescottes/piskel#672]
**Bug description**
When I attempt to zoom into my piskel to do see more clearly or do better detailing, the entire grid goes light grey. When this happens, you can't see, but you can still manipulate the piskel, although it doesn't help, because you can't see _what_ you're changing. When the pixel grid is on, you can see the piskel a little better, but not by much, not enough to make a good enough difference.

**Steps to reproduce the bug**
1. Open any piskel, new or previously created one.
2. Zoom in.
3. Piskel should suddenly turn light grey, obscuring vision.

**Environment details**
-Operating system: Chrome OS
-Browser (or offline application version): Google Chrome

**Sprite details**
-Number of frames: Any amount.
-Sprite resolution: It occurs in all of my piskels, all of varying sizes. If the sprite is too big to fit all on the piskel screen, it automatically opens up in light grey.
-Session duration: At start of opening the piskel.

Feel free to include a screenshot of the bug, a .piskel file of the sprite or anything else that can help us investigate.
![screenshot 2017-05-01 at 7 00 59 pm](https://cloud.githubusercontent.com/assets/28282200/25601394/947a1efc-2ea0-11e7-8c22-26dc899aa7e4.png)
![screenshot 2017-05-01 at 7 01 04 pm](https://cloud.githubusercontent.com/assets/28282200/25601396/98a0fe60-2ea0-11e7-95e1-dc90b8fc3f3e.png)
![screenshot 2017-05-01 at 7 01 08 pm](https://cloud.githubusercontent.com/assets/28282200/25601397/9bbdd82a-2ea0-11e7-9bec-216df3a2bd0f.png)

Please try to fix! Thank you so much!

**Comment by juliandescottes** [comment]
Hi, thanks for logging!

Unfortunately this is the same issue as #651 . 
It happens only on chromebooks and I don't own one so I can't investigate this at the moment :( 

I am closing this one as a duplicate, let's continue the discussion in #651
