### ISSUE TITLE
Consider hosting static pages with GitHub Pages.

### ISSUE THREAD

**Issue by ajayyy** [juliandescottes/piskel#679]
You said it costs around 100 dollars for hosting, why don't you host the static parts of the website with GitHub pages (or would that be infeasible).

Thanks for all your hard work, it's a really useful tool, and I'm happy you finally added an ad to help cover the costs.

**Comment by juliandescottes** [comment]
Thanks for the suggestion! 
I could indeed try to optimize a bit more how the statics are served, but most of it has infinite caching already and therefore has very little impact on the server. And static file serving is not costly with appengine (at least not for piskelapp).

My hosting costs are mostly related to DB operations. Right now we handle around 10 million sprites / 100GB of framesheet data. That's not something I can easily move out of my current technical stack.
My python appengine / datastore code is probably terrible though and I bet we could improve things there :) 

So, yes it's feasible, but I don't think it would be worth the effort at the moment :/

**Comment by ajayyy** [comment]
Ok, just thought it could be a way to lower your server costs.

**Comment by juliandescottes** [comment]
Closing for now. Let's move the discussion to piskel-website if needed!

**Comment by ajayyy** [comment]
Ok, thanks for responding!
